project:
  type: website
  output-dir: docs

website:
  title: "nethy-routes-repo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hut.qmd
      - transport.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



